[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
fren_tree = "HU7c5VwLom5ShB66EDWLa8vQPHBAkeTJ9yCtJYbuGS6E"

[programs.devnet]
fren_tree = "HU7c5VwLom5ShB66EDWLa8vQPHBAkeTJ9yCtJYbuGS6E"

[programs.mainnet]
fren_tree = "HU7c5VwLom5ShB66EDWLa8vQPHBAkeTJ9yCtJYbuGS6E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/joe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
